print('Hello, World')
print('Você já se perguntou o motivo para qual nascemos?')
print('Vivo me questionando, duvidando se há realmente algum propósito nisso tudo...')
print('As vezes, penso, onde está a realidade? Parece mentira, egoísta.')
print('Nascer, trabalhar, adquirir conhecimento e buscar a felicidade loucamemte para no fim, quando alcançada ou não, morrermos. Chamamos de vida.')
print('Talvez isso não devesse ser pensado, apenas vivido.')
print('Ou não.')
print('Se fica impossível encontrar um sentido no que desconhecemos, nada como se juntar a alguém tão perdido quanto.')
print('É nisso que muitos acabam resumindo no seu propósito, adquirir alguém permanentemente ao seu lado, para sentir um falsa ilusão de conforto de que pelo menos parte de sua vida foi completa.')
print('Eu questiono. No que se dá viver? Preciso do outro para ter a sensação de ganho ou para o egoísmo humano de ter alguém para puxar para baixo consigo nos piores momentos de sua vida até seu inevitável final?')